### ISSUE TITLE
openSUSE colored breeze cursors.

### ISSUE THREAD

**Issue by ghost** [openSUSE/plasma-opensuse#1]
Hi, i made a recolor of the breeze cursors using the official openSUSE colors that i think would fit here.
https://github.com/Swedneck/Breeze-geeko-cursor

**Comment by Vogtinator** [comment]
It would!
You can either make a pull request to include the final package as part of the `config-files` hierarchy, which means the cursors will be available as a subpackage of plasma5-openSUSE or make a package with your cursors and submit it to Factory, which means it'll be independant. 
I'm in favor of the latter, as I don't think that cursors are inherently plasma-dependant, which this repository is.

**Comment by ghost** [comment]
I'll try to figure out how to use OBS and make a package, thanks!

**Comment by Vogtinator** [comment]
User deleted his account :-(
