### ISSUE TITLE
openSUSE themes icons issues

### ISSUE THREAD

**Issue by ilvipero** [openSUSE/plasma-opensuse#11]
Hello, 
I previously opened a feature request on openSUSE tumbleweed bugzilla, regarding some missing icons on KDE plasma themes. One thing led to another and in the end I reviewed and modified openSUSE themes to fix missing icons and also create a more unified look. 

This is the bug i opened: https://bugzilla.opensuse.org/show_bug.cgi?id=1128854

Per last comment on the bug, I have the themes ready and packaged. I tested by importing manually on a number of openSUSE installations and I found no issues. 
Would you like me to upload those as pre-packaged KDE plasma themes for easier testing? or upload and create a pull request directly?

**Comment by Vogtinator** [comment]
Creating a PR would be very appreciated - thanks for your work!

**Comment by ilvipero** [comment]
Thanks for the confirmation. I created the pull request with modified themes. Feel free to let me know if I need to change something.

**Comment by Vogtinator** [comment]
#12 got merged
