### ISSUE TITLE
No icon in Plasma settings (about this system) after upgrade to Plasma 5.27 (Tumbleweed)

### ISSUE THREAD

**Issue by LordChaos73** [openSUSE/plasma-opensuse#20]
Apparently, distributor-logo.svg is missing after my system upgraded to Plasma 5.27.

Workaround:

sudo ln -s /usr/share/pixmaps/distribution-logos/square-hicolor.svg /usr/share/icons/hicolor/scalable/apps/distributor-logo.svg

**Comment by LordChaos73** [comment]
Before: https://pasteboard.co/y7T87WNSiz7K.png
After creating the symbolic link: https://pasteboard.co/Fp2hYOBtVkOP.png

**Comment by Vogtinator** [comment]
Hm, did I forget to add the dependendy after merging #19? I'll fix that.
